---
# This is an example playbook to execute Ansible tests.
# - name: Verify
#   hosts: all
#   gather_facts: false
#   tasks:
#   - name: Example assertion
#     assert:
#       that: true
- name: Verify
  hosts: all
  gather_facts: false
  user: vagrant
  tasks:
  - name: Snmpd is started
    systemd:
      name: snmpd
      enabled: true
      state: started
    register: Status
  # - name: Check snmpd status
  #   assert:
  #     that:
  #       - "Status.state == 'started'"
  #       - "Status.enabled == true"
