---
common__software:
  - iptables
  - iptables-services
  - httpd
  - git
  - epel-release
  - gcc
  - python3-pip
  - python3-devel
  - openssl-devel
  - python3-libselinux
  - docker
  # - molecule
